### ISSUE TITLE
Code detection is flaky when you define helpers for `inSpan`

### ISSUE THREAD

**Issue by parsonsmatt** [iand675/hs-opentelemetry#94] opened 2023-09-15 22:26 UTC
If you define an `inSpan` helper function like:

```haskell
myInSpan :: HasCallStack => Text -> IO a -> IO a
myInSpan name action = inSpan name defaultSpanArguments action
```

Then every use of `myInSpan` will be registered as the function that the span originates in. This is because `inSpan'` uses `callerAttributes` which only cares about the caller of `inSpan`.

**Comment by kakkun61** [comment] 2023-09-20 05:02
How about [`withFrozenCallStack`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-Stack.html#v:withFrozenCallStack)?

```haskell
myInSpan :: HasCallStack => Text -> IO a -> IO a
myInSpan name action = withFrozenCallStack $ inSpan name defaultSpanArguments action
```

**Comment by parsonsmatt** [comment] 2023-09-20 18:27
That does work, thank you! But now I am finding that I'm actually a bit confused about the intention of `callerAttributes`.

```haskell
inSpan
  :: (MonadUnliftIO m, HasCallStack)
  => Tracer
  -> Text
  -> SpanArguments
  -> m a
  -> m a
inSpan t n args m = inSpan'' t n (args {attributes = H.union (attributes args) callerAttributes}) (const m)

callerAttributes :: (HasCallStack) => H.HashMap Text Attribute
callerAttributes = case getCallStack callStack of
  _ : _ : caller : _ -> srcAttributes caller
  _ -> mempty
```

`callerAttributes` skips it's own entry, and then `inSpan`'s entry, and finally gives the entry for the caller of `inSpan`. However, this is a bit odd

```haskell
foo :: HasCallStack => IO ()
foo = bar

bar :: HasCallStack => IO ()
bar = inSpan "asdf" defaultSpanArguments do print 10
```

With the current implementation, I get `code.function` of `bar` and `code.lineno` pointing to the *callsite* of `bar`. And, if `bar` does not have a `HasCallStack` constraint, then I get no `code.function` or `code.lineno`. But this is unfortunate, because the `inSpan` entry that we skip carries the *callsite* of `inSpan`, which would be useful for us to know that it was called in `bar`.

**Comment by aaronallen8455** [comment] 2023-10-16 03:15
This seems like a bug. The issue is that `callStack` does not include the entry for its call site (within the body of `callerAttributes` in this case) and so in the pattern match on `getCallStack callStack`, the first dropped entry is the callsite of `callerAttributes` while the second is the callsite of `inSpan` and so `caller` is the callsite of the function that called `inSpan` (if it possesses a `HasCallStack` constraint). `caller` should instead be the callsite of `inSpan` which would match the behavior prior to version 0.1.0.0.

**Comment by Profpatsch** [comment] 2024-07-28 11:44
I feel like the best solution here would be to wrap every `inSpan` function in `withFrozenCallStack` and just use the frozen call stack directly here. No weird heuristics necessary if the user has direct control of the call stack that is used.

**Comment by Profpatsch** [comment] 2024-07-28 11:46
I did that in https://github.com/iand675/hs-opentelemetry/pull/139 (WIP) and it looks like it leads to better results.

**Comment by michaelpj** [comment] 2024-07-28 19:52
I tried to fix this in https://github.com/iand675/hs-opentelemetry/pull/137

> I feel like the best solution here would be to wrap every inSpan function in withFrozenCallStack and just use the frozen call stack directly here. No weird heuristics necessary if the user has direct control of the call stack that is used.

The reason I didn't suggest that is that it means that `callerAttributes` etc. don't work properly unless the call stack is frozen. But they are actually used in a few places and are even exported from the library! So I thought it was best to try and make them work with both a frozen and unfrozen call stack. I think my PR does a reasonable job of that? Do you have a problematic case in mind?

**Comment by Profpatsch** [comment] 2024-07-29 10:02
> Do you have a problematic case in mind?

https://github.com/iand675/hs-opentelemetry/blob/967ba859169978add5c6c82b6ab39ff789fbedd8/api/src/OpenTelemetry/Trace/Monad.hs#L60-L86

These provide another layer of wrapping, which kinda breaks the “upwards counting” of `callerAttributes`.

I noticed that a lot of things are exported that looks like internals, yes, so backwards compat for many of these features is already kinda annoying.

**Comment by michaelpj** [comment] 2024-07-29 10:16
Yes, I would agree that those should use `withFrozenCallStack`. The point of my changes is that if they do that (and remove the call stack entry for themselves) it will now actually work, whereas before it was broken.

**Comment by michaelpj** [comment] 2024-11-13 11:22
I tentatively think this is as good as it's likely to get, so closing. In some cases you may also need to pop the call stack to get your helper off the stack, but I think you can now get the right behaviour, and it's not at all clear to me that we can reliably do better.

**Closed by michaelpj** 2024-11-13 11:22 UTC
